### PR TITLE
Change to shared linking to Boost on Mac and Linux.

### PR DESCRIPTION
**Pull request by inati**

### CODE REVIEW

**Comment by hansenms** [comment]
Why? I seem to remember that we went for static linking to make it as simple as possible to make a distributable converter. What's the advantage of switching back?

**Comment by inati** [comment]
I’m 50/50 on this one.  The advantage of staticly linking boost isn’t really that great.  The program is still dynamically linked to ismrmrd and hdf5, so  we can’t just send a single binary.  The downside of static linking is that at build time we need to have the static versions of the boost libraries compiled - which is not the case by default on some systems.  Anyway, if we don’t make this change, I can work around it on the other side.  Either way is fine with me - so your call.

-SI

**Comment by hansenms** [comment]
We clearly have work to do to statically link the rest of the libraries, but that doesn't mean we should give up, does it?

On which systems do the static libs not get installed by default? What workaround is needed exactly?

This is not a big deal, I just hate changing build setups without a good reason.

Boost static libs are installed on the Mac when I install with homebrew. They are also on my Ubuntu.

------

**Comment by inati** [comment]
Okay, that makes sense.  Let’s make that a clear long term goal of relatively low priority.

Using anaconda on mac and linux they are not installed by default, but that’s okay, I’ll just make another recipe to build them statically and be done with it.  I’ll withdraw the pull request.

**Comment by inati** [comment]
Pull request withdrawn

**Comment by hansenms** [comment]
Just out if curiosity. How is anaconda related to the converter? Isn't that a python thing?

------

**Comment by inati** [comment]
Oh no, it is so much more than a python thing :-)  I’m almost done getting the whoe gadgetron environment working on the Biowulf cluster using anaconda as a package manager that is cross-platform and super simple to use.  We’ll see.

**Comment by hansenms** [comment]
Well put in a PR where it is optional then. It could just be a CMAKE option.

------

**Comment by inati** [comment]
Okay how about this?  Seems to do the trick.  The default behavior is unchanged, and if I configure with
-DBUILD_DYNAMIC=YES
I get a dynamic link to lib_boost_xxxx

**Pull request merged**
