### PR TITLE
Fix noise bandwidth in Numaris/X

### PR DESCRIPTION
**Pull request by kspaceKelvin**
Fix detection of Numaris/X data and update stylesheet to account for missing imageColumns. This incorporates changes by @xueh2 in #106 , so I'm closing that one.

Prior to this patch, Numaris/X noise dependency data wasn't correctly detected and an incorrect noise bandwidth was returned by compute_noise_sample_in_us().

@ACampbellWashburn @rajramasawmy @ahsanjav I think this sorts out the issue we discussed last week.

### CODE REVIEW

**Comment by hansenms** [comment]
This looks OK to me, but we should have @xueh2 / @rajramasawmy  / @ahsanjav weigh in since they probably have data to test with.

**Comment by rajramasawmy** [comment]
Just tried this out on our XA60, but the dwell time of the noise (5e-6s) was being set for the acquisition data as well (tested for a range of bandwidths at 2 resolutions)

**Comment by rajramasawmy** [comment]
I'll send the dats to you Kelvin to test

**Comment by xueh2** [comment]
Looks ok to me too. But need phantom test to make sure noise BW is correct.

**Comment by rajramasawmy** [comment]
ignore me this works just fine

**Review by dchansen — APPROVED** [review]

**Pull request merged**
