### PR TITLE
Set default output filename to match base path of input

### PR DESCRIPTION
**Pull request by kspaceKelvin**
This sets a default output filename to match the input name so that it's easier to use.

@hansenms If you have a cleaner way of implementing, please suggest it.

### CODE REVIEW

**Comment by hansenms** [comment]
Please merge in the master branch.

I could not from fast searching find a quick way to set a default value from another value in boost options, so maybe it is not possible. @dchansen do you have experience with this? This is not the end of the world here, but it just feels a bit ugly to set the string empty (and so default value which shows up in the help text is empty). but then when the default value is the default value, we actually overwrite it, so it is not the default. Seems bad.

**Comment by kspaceKelvin** [comment]
Are you asking me to merge into the master branch of my fork?  I thought GitHub would have figured out the diff now that the skipSyncData PR has been merged, but I still see it in the diff here.  I'm evidently not wise in the ways of the GitHub...

**Comment by hansenms** [comment]
you need to merge master into your branch...or rebase your branch, whichever you prefer. If you rebase, you may have to force push, so I would merge the master.

**Comment by hansenms** [comment]
If we cannot find a way to specify the default in terms of another parameter, I would recommend setting the default to something like `<input file without extension>.mrd` so that it shows up in the help text and then replace that.

**Comment by kspaceKelvin** [comment]
Ah, ok, I fetched the upstream and we're good.  Let's wait for David to comment on if it's possible to directly set the default value as you suggested.

**Review by dchansen — APPROVED** [review]

**Comment by hansenms** [comment]
Looks good.

**Pull request merged**
