### PR TITLE
Add flags for phase stabilization scans

### PR DESCRIPTION
**Pull request by pehses**
Until now, the PHASESTABSCAN flag is completely ignored during conversion, which makes it impossible to correctly reconstruct some Cartesian gradient-echo data that acquire phase stabilization scans (additional non-phase-encoded ADC per TR).

I fixed this by converting the corresponding evalInfoMask bit 15 to ISMRMRD_ACQ_IS_NAVIGATION_DATA. Currently, ISMRMRD_ACQ_IS_NAVIGATION_DATA stores evalInfoMask bit 1 which is already accessible via ISMRMRD_ACQ_IS_RTFEEDBACK_DATA.

If the current behavior should be preserved, I propose to either introduce a new flag to ISMRMRD, or alternatively to make use of one of the existing USER_ flags.

Note that there's also a 'MDH_REFPHASESTABSCAN' flag (bit 14) that is currently ignored but may be useful for some users.

### CODE REVIEW

**Comment by hansenms** [comment]
We may need to pull in some opinions here, but I think this was intended for things like respiratory navigators in cardiac imaging, so the proposed change here is likely a breaking one for some users. Maybe we can get a consult from @kspaceKelvin and/or @xueh2 ?

**Comment by hansenms** [comment]
@kspaceKelvin , I think you were going to comment here.

**Comment by kspaceKelvin** [comment]
As discussed, I would prefer not to modify meaning of ``ISMRMRD_ACQ_IS_NAVIGATION_DATA``, as this is currently used by some applications to indicate some sort of motion navigation data.  As there are still some unused flags ISMRMRD, I've added them via this pull request: https://github.com/ismrmrd/ismrmrd/pull/194

@pehses Can you try using the following commit along with the above ISMRMRD PR to see if that addresses your use case?
https://github.com/kspaceKelvin/siemens_to_ismrmrd/commit/f09466336e2e19100391a7d8bb12df3437dfeca3

**Comment by pehses** [comment]
Yes, that's exactly what I needed. Thanks @kspaceKelvin and @hansenms!

**Comment by hansenms** [comment]
@pehses: Few things:

1. we need to update this PR to use the new flags @kspaceKelvin introduced
2. we also need to update the dependency file for ISMRMRD to target the hash of that commit that just merged. 
3. And we need to bump the version of the converter.

**Comment by hansenms** [comment]
@pehses and update the title to reflect what actually would be happeninng.

**Comment by kspaceKelvin** [comment]
@pehses Tasks 1 and 2 should be covered by my PR on your branch here: https://github.com/pehses/siemens_to_ismrmrd/pull/2. I bumped the version to 1.1.0 as there is a new feature.  This probably obviates the need for https://github.com/ismrmrd/siemens_to_ismrmrd/pull/86

**Comment by pehses** [comment]
Ok, I changed the title and merged @kspaceKelvin's pull request. I also reverted my initial change so that ISMRMRD_ACQ_IS_NAVIGATION_DATA again points to Siemens' Bit 1 (RTFEEDBACK).

Thanks again @kspaceKelvin and @hansenms!

**Review by hansenms — APPROVED** [review]

**Pull request merged**
