### PR TITLE
Add option to skip parsing of syncdata

### PR DESCRIPTION
**Pull request by kspaceKelvin**
Add command line option to skip parsing of syncdata, which has changed formats in XA31

### CODE REVIEW

**Comment by dchansen** [comment]
If we are changing the default outputfile, let's do it the easy way and also use the .mrd extension.

**Comment by kspaceKelvin** [comment]
Haha oops, forgot that it would keep tracking on my master branch as I was still making changes for my own purposes. ;p

I'm ok with changing the default extension to mrd, but I'm not sure if this would break anything else outside of this repo as I'm not sure it's been used yet.  If not, then it'd be nice to have our own extension.

**Comment by hansenms** [comment]
Looks fine, but I would not change the default output file in this PR. I think that should be a separate PR. Also, I think there is a way to set the default from another input so that we don't have the default be `""` and then some code that fixes that later. But again, I would take that in a separate PR.

**Comment by kspaceKelvin** [comment]
Ok it's back to just the syncdata commit now.  I moved the default filenames stuff into a different branch that we can discuss in another PR.

**Review by hansenms — APPROVED** [review]

**Comment by Andrew-Dupuis** [comment]
@kspaceKelvin Is there any good documentation of the new syncdata format that we might be able to roll in, or is it no longer needed? We're working with some EKG/PilotTone/Respiratory data right now and while using the skipSyncData flag works for the dat->ismrmrd conversion, we're having some issues during the recon on VA31 datasets that don't exist on VA20. There's a decent chance we've missed something else, but wanted to check on this aspect first in case the missing data is actually just being "skipped" now

**Pull request merged**
